services:
  nginx:
    build: ./requirement/nginx
    image: "nginx"
    container_name: run-nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress: 
    build: ./requirement/wordpress
    image: "wordpress"
    container_name: run-wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}

    secrets:
      - mysql_user_password
      - wp_admin_password
      - wp_user_password

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception

  mariadb:
    build: ./requirement/mariadb
    image: "mariadb"
    container_name: run-mariadb
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    secrets:
      - mysql_root_password
      - mysql_user_password

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception

  redis:
    build: ./requirement/bonus/redis
    image: "redis"
    container_name: run-redis
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - inception

  static:
    build: ./requirement/bonus/static
    image: "static-website"
    container_name: run-static-website
    restart: always
    networks:
      - inception

  ftp:
    build: ./requirement/bonus/FTP
    image: "ftp"
    container_name: run-ftp
    restart: unless-stopped

    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASV_ADDRESS: ${FTP_PASV_ADDRESS}
    secrets:
      - ftp_password

    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    networks:
      - inception

  adminer:
    build: ./requirement/bonus/Adminer
    image: "adminer"
    container_name: run-adminer
    restart: always
    ports:
      - "8888:8888"
    networks:
      - inception

  portainer:
    build: ./requirement/bonus/portainer
    image: "portainer"
    container_name: run-portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/portainer
  
networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    environment: MYSQL_ROOT_PASSWORD
  mysql_user_password:
    environment: MYSQL_PASSWORD
  ftp_password:
    environment: FTP_PASSWORD
  wp_admin_password:
    environment: WP_ADMIN_PASSWORD
  wp_user_password:
    environment: WP_USER_PASSWORD