

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name aybouatr.42.fr;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        server_tokens off;

        root /var/www/html;
        index index.php index.html;

        # WordPress
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # PHP-FPM
        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # location /ftp/ {
        # proxy_pass http://ftp:2121/;
        # }

        # Static assets
        location ~* \.(jpg|jpeg|png|gif|ico|svg|css|js|woff|woff2|ttf|eot)$ {
            expires max;
            access_log off;
            log_not_found off;
        }

        # Redirect /portainer
        location = /portainer {
            return 301 https://$host:9443/#!/init/admin;
        }

        location /adminer {
        	proxy_pass http://adminer:8888/;
    	}

        # Redirect /portainer/
        location /portainer/ {
            return 301 https://$host:9443/#!/init/admin;
        }

        # Redirect /static/
        location /static/ {
            	proxy_pass http://static:80/;
        	}
        


    }
